### PR TITLE
fix(delete functions): Remove Stat Cache after successful operation

### PR DESCRIPTION
**Pull request by Hemant-Mann**
Fix for #31 

Remove Stat Cache after successful operation

### CODE REVIEW

**Comment by PVince81** [comment]
Didn't we have this class in core now ? Would be good if a future version of the app bases itself on the core adapter which was merged already

**Comment by Hemant-Mann** [comment]
Yes you are right this class was merged into core but since Dropbox was to be released before core this was not removed at that time

We can definitely remove this class from here after #27 is merged then we can do some changes in Dropbox to accommodate this

**Comment by PVince81** [comment]
@Hemant-Mann sounds like a good plan!

**Comment by patrickjahns** [comment]
@Hemant-Mann 
can you create a ticket for the backlog?

**Comment by Hemant-Mann** [comment]
Yes @patrickjahns we should merge this
I tested this branch and i was able to delete files on first try

But a quick regression could be done to make sure it does not do anything unanticipated

**Comment by Hemant-Mann** [comment]
Merge this?

**Pull request merged**
