### PR TITLE
Dropbox access library updated.

### PR DESCRIPTION
**Pull request by ahherrera**
Dropbox access library updated.
Issue: https://github.com/owncloud/enterprise/issues/5135

### CODE REVIEW

**Comment by jnweiger** [comment]
@IljaN https://github.com/kunalvarma05/dropbox-php-sdk/pull/196 was merged. How do we proceed here?

**Review by jnweiger — CHANGES_REQUESTED** [review]
This seems obsolete. We currently have this 

```
   "require": {
        "kunalvarma05/dropbox-php-sdk": "^0.2",
        "hemant-mann/flysystem-dropbox": "^1.0"
```

**Comment by mmattel** [comment]
Consider closing, because master already contains updates by @phil-davis from August 1st:
```
"kunalvarma05/dropbox-php-sdk": "^0.4.1",
"hemant-mann/flysystem-dropbox": "^1.0.5"
```
which both are the latest releases available,
and guzzle is on  - as far I can see in the composer.lock file - on v7

@jvillafanez what is your opinion?

**Comment by jvillafanez** [comment]
https://github.com/owncloud/files_external_dropbox/pull/147 was tested with the latest versions available, so I don't think this is needed. I vote for closing this issue without merging.

**Comment by mmattel** [comment]
Closing as outdated, see discussion above

**Pull request closed without merging**
