### PR TITLE
Standardize CI

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #35 

1st commit:
- massage ``Makefile`` to have targets for unit tests, phan, phpstan
- ``phpunit.xml`` up to root dir
- move unit tests down into ``tests/unit``
- add default configs for ``php-cs-fixer`` ``phan`` and ``phpstan``

2nd commit:
- ``make test-php-style-fix`` and commit the source code changes

3rd commit:
- implement drone with coding standard and PHP unit tests

4th commit:
- remove the PHP unit test matrix entries. Read comment https://github.com/owncloud/files_external_dropbox/pull/46#issuecomment-446087702

### CODE REVIEW

**Comment by phil-davis** [comment]
I can run the unit tests locally with ``make test-php-unit`` and the script infrastructure works. Of course the tests give lots of fails because the whole "Dropbox App" settings have to be set up. But at least I know that the unit test script changes are working.

**Comment by davitol** [comment]
@phil-davis as you commented before, you need to first manually configure Dropbox to work correctly in the web UI. Also you need to browse to ```https://www.dropbox.com/developers/apps/```in your account and add the urls of your oC server

**e.g.**

screen shot 2018-12-11 at 09 16 36

**Comment by phil-davis** [comment]
The challenge is that my local test ownCloud is just in a local docker network 172.17.0.1 so it is not on the public internet. I will leave this PR as it is, and people can review and approve if they are happy.

**Comment by skshetry** [comment]
`tests/bootstrap.php` doesnot seem to use anything special. It'd be better if we could use `core` bootstrap. Maybe in this PR or another.

**Comment by phil-davis** [comment]
@skshetry we do not want to mess too much with the unit tests, which are difficult to get running.
So this PR is just about "moderate refactoring" to get CI scripts more current, apply code style, and run code style checks in CI.

**Pull request merged**
